-- which-key 提示的简体中文翻译表
--
-- 工作方式：which-key 显示每个按键说明（desc）之前，会先执行 opts.replace.desc 里的规则，
-- lua/plugins/which-key-zh.lua 在规则末尾加了一个函数：拿英文原文到下面的表里查中文。
-- * exact    ：整句对照（原文 → 中文），覆盖 LazyVim 及已启用 Extras 的全部按键说明
-- * toggles  ：开关类按键的名称（显示为“启用 xxx / 禁用 xxx”）
-- * patterns ：按规律批量翻译（Lua 模式匹配），用于无法逐条列举的说明
-- 查不到的原文会原样显示。发现遗漏时，把英文原文（去掉开头的 + 或 :）加进 exact 即可。
local M = {}

M.exact = {
  -- ── 分组（按 <leader> 空格键 后看到的第一级菜单）──────────────────────
  ["buffer"] = "缓冲区（已打开的文件）",
  ["code"] = "代码",
  ["debug"] = "调试",
  ["diagnostics/quickfix"] = "诊断 / 快速修复列表",
  ["file/find"] = "文件 / 查找",
  ["git"] = "Git 版本控制",
  ["goto"] = "跳转",
  ["hunks"] = "Git 改动块",
  ["noice"] = "消息通知（Noice）",
  ["profiler"] = "性能分析",
  ["quit/session"] = "退出 / 会话",
  ["search"] = "搜索",
  ["surround"] = "包围符号",
  ["tabs"] = "标签页",
  ["ui"] = "界面开关",
  ["windows"] = "窗口",
  ["window"] = "窗口",
  ["fold"] = "折叠",
  ["next"] = "下一个",
  ["prev"] = "上一个",
  ["inside"] = "内部（不含边界）",
  ["around"] = "外围（含边界）",
  ["last"] = "上一个",
  ["marks"] = "标记",
  ["registers"] = "寄存器",

  -- ── 文件 / 查找 ───────────────────────────────────────────────────────
  ["Buffers"] = "已打开的文件",
  ["Buffers (all)"] = "已打开的文件（全部）",
  ["Find Config File"] = "查找 nvim 配置文件",
  ["Find Files (Root Dir)"] = "查找文件（项目根目录）",
  ["Find Files (cwd)"] = "查找文件（当前目录）",
  ["Find Files (git-files)"] = "查找文件（仅 Git 跟踪的）",
  ["Recent"] = "最近打开的文件",
  ["Recent (cwd)"] = "最近打开的文件（当前目录）",
  ["Projects"] = "项目列表",
  ["New File"] = "新建文件",
  ["Explorer Snacks (root dir)"] = "文件树（项目根目录）",
  ["Explorer Snacks (cwd)"] = "文件树（当前目录）",
  ["Terminal (Root Dir)"] = "终端（项目根目录）",
  ["Terminal (cwd)"] = "终端（当前目录）",
  ["Save File"] = "保存文件",
  ["Open file with system app"] = "用系统程序打开文件",
  ["Open with system app"] = "用系统程序打开",
  ["Go to file under cursor"] = "打开光标处的文件路径",

  -- 启动页菜单（lua/plugins/dashboard-zh.lua 使用）
  ["Find File"] = "查找文件",
  ["Find Text"] = "全文搜索",
  ["Recent Files"] = "最近打开的文件",
  ["Config"] = "nvim 配置文件",
  ["Lazy Extras"] = "LazyVim 扩展（Extras）",
  ["Quit"] = "退出",

  -- ── 搜索 ─────────────────────────────────────────────────────────────
  ["Grep (Root Dir)"] = "全文搜索（项目根目录）",
  ["Grep (cwd)"] = "全文搜索（当前目录）",
  ["Grep Open Buffers"] = "在已打开的文件中搜索",
  ["Buffer Lines"] = "搜索当前文件的行",
  ["Visual selection or word (Root Dir)"] = "搜索选中内容或光标处单词（项目根目录）",
  ["Visual selection or word (cwd)"] = "搜索选中内容或光标处单词（当前目录）",
  ["Word (Root Dir)"] = "搜索光标处单词（项目根目录）",
  ["Word (cwd)"] = "搜索光标处单词（当前目录）",
  ["Selection (Root Dir)"] = "搜索选中内容（项目根目录）",
  ["Selection (cwd)"] = "搜索选中内容（当前目录）",
  ["Search and Replace"] = "搜索并替换（多文件）",
  ["Search History"] = "搜索历史",
  ["Command History"] = "命令历史",
  ["Commands"] = "所有命令",
  ["Keymaps"] = "所有快捷键",
  ["Help Pages"] = "帮助文档",
  ["Man Pages"] = "Man 手册",
  ["Highlights"] = "高亮组",
  ["Icons"] = "图标",
  ["Jumps"] = "跳转历史",
  ["Marks"] = "标记列表",
  ["Registers"] = "寄存器列表",
  ["Autocmds"] = "自动命令",
  ["Colorschemes"] = "切换配色主题",
  ["Resume"] = "重新打开上次的搜索",
  ["Undotree"] = "撤销历史树",
  ["Location List"] = "位置列表",
  ["Quickfix List"] = "快速修复列表",
  ["Diagnostics"] = "诊断（全部文件）",
  ["Buffer Diagnostics"] = "诊断（当前文件）",
  ["Search for Plugin Spec"] = "搜索插件配置",
  ["Todo"] = "TODO 注释",
  ["Todo/Fix/Fixme"] = "TODO / FIX / FIXME 注释",
  ["Noice Picker (Telescope/FzfLua)"] = "消息搜索",
  ["Notification History"] = "通知历史",
  ["Treesitter Search"] = "语法树搜索",
  ["Search forward"] = "向下搜索",
  ["Search backward"] = "向上搜索",
  ["Search forwards and select"] = "向下搜索并选中",
  ["Search backwards and select"] = "向上搜索并选中",
  ["Next Search Result"] = "下一个搜索结果",
  ["Prev Search Result"] = "上一个搜索结果",
  ["Cycle backwards through results"] = "反向切换搜索结果",
  ["Escape and Clear hlsearch"] = "退出并清除搜索高亮",
  ["Redraw / Clear hlsearch / Diff Update"] = "重绘屏幕 / 清除搜索高亮 / 刷新对比",

  -- ── 代码 / LSP ───────────────────────────────────────────────────────
  ["Code Action"] = "代码操作（快速修复等）",
  ["Source Action"] = "源码操作",
  ["Format"] = "格式化",
  ["Format Injected Langs"] = "格式化嵌入的其他语言",
  ["Format selection or buffer"] = "格式化选中内容或整个文件",
  ["Rename"] = "重命名符号",
  ["Rename File"] = "重命名文件（同步更新引用）",
  ["Run Codelens"] = "运行 Codelens",
  ["Refresh & Display Codelens"] = "刷新并显示 Codelens",
  ["Lsp Info"] = "语言服务器信息",
  ["Goto Definition"] = "跳转到定义",
  ["Goto Declaration"] = "跳转到声明",
  ["Goto Implementation"] = "跳转到实现",
  ["Goto T[y]pe Definition"] = "跳转到类型定义",
  ["Goto Source Definition"] = "跳转到源码定义",
  ["References"] = "查找引用",
  ["File References"] = "查找引用当前文件的地方",
  ["Next Reference"] = "下一个引用",
  ["Prev Reference"] = "上一个引用",
  ["Hover"] = "悬浮文档",
  ["Signature Help"] = "函数参数提示",
  ["C[a]lls Incoming"] = "谁调用了它",
  ["C[a]lls Outgoing"] = "它调用了谁",
  ["LSP Symbols"] = "当前文件的符号",
  ["LSP Workspace Symbols"] = "整个项目的符号",
  ["Organize Imports"] = "整理 import",
  ["Add missing imports"] = "补全缺失的 import",
  ["Remove unused imports"] = "移除未使用的 import",
  ["Fix all diagnostics"] = "修复全部可自动修复的问题",
  ["Select TS workspace version"] = "选择项目使用的 TypeScript 版本",
  ["Line Diagnostics"] = "当前行的诊断信息",
  ["Show diagnostics under the cursor"] = "显示光标处的诊断信息",
  ["Next Diagnostic"] = "下一个诊断",
  ["Prev Diagnostic"] = "上一个诊断",
  ["Next Error"] = "下一个错误",
  ["Prev Error"] = "上一个错误",
  ["Next Warning"] = "下一个警告",
  ["Prev Warning"] = "上一个警告",
  ["Jump to the first diagnostic in the current buffer"] = "跳到本文件第一个诊断",
  ["Jump to the last diagnostic in the current buffer"] = "跳到本文件最后一个诊断",
  ["Mason"] = "Mason 工具管理",
  ["Inspect Pos"] = "查看光标处的高亮信息",
  ["Inspect Tree"] = "查看语法树",
  ["Keywordprg"] = "查询关键字文档",
  ["Add Comment Above"] = "在上方添加注释",
  ["Add Comment Below"] = "在下方添加注释",
  ["Toggle comment"] = "注释 / 取消注释",
  ["Toggle comment line"] = "注释 / 取消注释当前行",
  ["Comment textobject"] = "注释块",
  ["vim.lsp.buf.code_action()"] = "代码操作",
  ["vim.lsp.buf.document_symbol()"] = "当前文件的符号",
  ["vim.lsp.buf.hover()"] = "悬浮文档",
  ["vim.lsp.buf.implementation()"] = "跳转到实现",
  ["vim.lsp.buf.references()"] = "查找引用",
  ["vim.lsp.buf.rename()"] = "重命名符号",
  ["vim.lsp.buf.type_definition()"] = "跳转到类型定义",
  ["vim.lsp.codelens.run()"] = "运行 Codelens",
  ["vim.snippet.jump if active, otherwise <Tab>"] = "跳到代码片段下一处（否则输入 Tab）",
  ["vim.snippet.jump if active, otherwise <S-Tab>"] = "跳到代码片段上一处（否则输入 Shift+Tab）",

  -- ── Trouble（问题列表面板）─────────────────────────────────────────────
  ["Diagnostics (Trouble)"] = "诊断面板（全部文件）",
  ["Buffer Diagnostics (Trouble)"] = "诊断面板（当前文件）",
  ["Symbols (Trouble)"] = "符号面板",
  ["LSP references/definitions/... (Trouble)"] = "LSP 引用 / 定义面板",
  ["Location List (Trouble)"] = "位置列表面板",
  ["Quickfix List (Trouble)"] = "快速修复列表面板",
  ["Todo (Trouble)"] = "TODO 面板",
  ["Todo/Fix/Fixme (Trouble)"] = "TODO / FIX / FIXME 面板",
  ["Next Trouble/Quickfix Item"] = "下一个问题 / 修复项",
  ["Previous Trouble/Quickfix Item"] = "上一个问题 / 修复项",
  ["Next Todo Comment"] = "下一个 TODO 注释",
  ["Previous Todo Comment"] = "上一个 TODO 注释",

  -- ── Git ──────────────────────────────────────────────────────────────
  ["Lazygit (Root Dir)"] = "Lazygit（项目根目录）",
  ["Lazygit (cwd)"] = "Lazygit（当前目录）",
  ["Git Status"] = "Git 状态",
  ["Git Log"] = "Git 提交历史",
  ["Git Log (cwd)"] = "Git 提交历史（当前目录）",
  ["Git Current File History"] = "当前文件的提交历史",
  ["Git Blame Line"] = "查看当前行是谁改的",
  ["Git Browse (open)"] = "在浏览器中打开（远程仓库）",
  ["Git Browse (copy)"] = "复制远程仓库链接",
  ["Git Diff (hunks)"] = "Git 改动列表",
  ["Git Diff (origin)"] = "与远程分支对比",
  ["Git Diff (files)"] = "有改动的文件",
  ["Git Stash"] = "Git 暂存栈（stash）",
  ["GitHub Issues (open)"] = "GitHub Issue（未关闭）",
  ["GitHub Issues (all)"] = "GitHub Issue（全部）",
  ["GitHub Pull Requests (open)"] = "GitHub PR（未关闭）",
  ["GitHub Pull Requests (all)"] = "GitHub PR（全部）",
  ["Blame Line"] = "当前行的 blame 信息",
  ["Blame Buffer"] = "整个文件的 blame 信息",
  ["Diff This"] = "与暂存区对比",
  ["Diff This ~"] = "与上一次提交对比",
  ["Stage Hunk"] = "暂存此改动块",
  ["Reset Hunk"] = "撤销此改动块",
  ["Stage Buffer"] = "暂存整个文件",
  ["Reset Buffer"] = "撤销整个文件的改动",
  ["Undo Stage Hunk"] = "取消暂存改动块",
  ["Preview Hunk Inline"] = "行内预览改动块",
  ["Next Hunk"] = "下一个改动块",
  ["Prev Hunk"] = "上一个改动块",
  ["First Hunk"] = "第一个改动块",
  ["Last Hunk"] = "最后一个改动块",
  ["GitSigns Select Hunk"] = "选中改动块",

  -- ── 缓冲区（已打开的文件）────────────────────────────────────────────
  ["Delete Buffer"] = "关闭当前文件",
  ["Delete Buffer and Window"] = "关闭当前文件和窗口",
  ["Delete Other Buffers"] = "关闭其他文件",
  ["Delete Buffers to the Left"] = "关闭左侧的文件",
  ["Delete Buffers to the Right"] = "关闭右侧的文件",
  ["Delete Non-Pinned Buffers"] = "关闭未固定的文件",
  ["Delete Invisible Buffers"] = "关闭不可见的文件",
  ["Toggle Pin"] = "固定 / 取消固定",
  ["Pick Buffer"] = "选择文件",
  ["Next Buffer"] = "下一个文件",
  ["Prev Buffer"] = "上一个文件",
  ["Move buffer next"] = "文件标签右移",
  ["Move buffer prev"] = "文件标签左移",
  ["Switch to Other Buffer"] = "切换到上一个文件",
  ["Switch Buffer"] = "切换文件",
  ["Toggle Scratch Buffer"] = "打开 / 关闭草稿本",
  ["Select Scratch Buffer"] = "选择草稿本",
  ["Profiler Scratch Buffer"] = "性能分析草稿本",

  -- ── 窗口 ─────────────────────────────────────────────────────────────
  ["Split Window Below"] = "向下分屏",
  ["Split Window Right"] = "向右分屏",
  ["Split window"] = "水平分屏",
  ["Split window vertically"] = "垂直分屏",
  ["Delete Window"] = "关闭窗口",
  ["Quit a window"] = "关闭窗口",
  ["Close all other windows"] = "关闭其他所有窗口",
  ["Switch windows"] = "切换窗口",
  ["Go to Left Window"] = "移到左边窗口",
  ["Go to Right Window"] = "移到右边窗口",
  ["Go to Upper Window"] = "移到上边窗口",
  ["Go to Lower Window"] = "移到下边窗口",
  ["Go to the left window"] = "移到左边窗口",
  ["Go to the right window"] = "移到右边窗口",
  ["Go to the up window"] = "移到上边窗口",
  ["Go to the down window"] = "移到下边窗口",
  ["Increase Window Height"] = "增加窗口高度",
  ["Decrease Window Height"] = "减少窗口高度",
  ["Increase Window Width"] = "增加窗口宽度",
  ["Decrease Window Width"] = "减少窗口宽度",
  ["Increase height"] = "增加高度",
  ["Decrease height"] = "减少高度",
  ["Increase width"] = "增加宽度",
  ["Decrease width"] = "减少宽度",
  ["Max out the height"] = "高度最大化",
  ["Max out the width"] = "宽度最大化",
  ["Equally high and wide"] = "所有窗口等分大小",
  ["Move window to far left"] = "窗口移到最左",
  ["Move window to far right"] = "窗口移到最右",
  ["Move window to far top"] = "窗口移到最上",
  ["Move window to far bottom"] = "窗口移到最下",
  ["Break out into a new tab"] = "移到新标签页",
  ["Swap current with next"] = "与下一个窗口交换",
  ["Window Hydra Mode (which-key)"] = "窗口连续操作模式",
  ["Buffer Keymaps (which-key)"] = "当前文件的快捷键",

  -- ── 标签页 ───────────────────────────────────────────────────────────
  ["New Tab"] = "新建标签页",
  ["Close Tab"] = "关闭标签页",
  ["Close Other Tabs"] = "关闭其他标签页",
  ["First Tab"] = "第一个标签页",
  ["Last Tab"] = "最后一个标签页",
  ["Next Tab"] = "下一个标签页",
  ["Previous Tab"] = "上一个标签页",
  ["Go to next tab page"] = "下一个标签页",
  ["Go to previous tab page"] = "上一个标签页",

  -- ── 退出 / 会话 / 其他 ────────────────────────────────────────────────
  ["Quit All"] = "退出全部",
  ["Restore Session"] = "恢复会话（上次打开的文件）",
  ["Restore Last Session"] = "恢复最近一次会话",
  ["Select Session"] = "选择会话",
  ["Don't Save Current Session"] = "本次不保存会话",
  ["Session"] = "会话",
  ["Lazy"] = "Lazy 插件管理",
  ["LazyVim Changelog"] = "LazyVim 更新日志",
  ["Redirect Cmdline"] = "重定向命令行输出",
  ["Noice All"] = "全部消息",
  ["Noice History"] = "消息历史",
  ["Noice Last Message"] = "最后一条消息",
  ["Dismiss All"] = "清除所有消息",
  ["Dismiss All Notifications"] = "清除所有通知",
  ["Scroll Forward"] = "向下滚动",
  ["Scroll Backward"] = "向上滚动",
  ["Move Down"] = "下移当前行",
  ["Move Up"] = "上移当前行",
  ["Add empty line above cursor"] = "在上方插入空行",
  ["Add empty line below cursor"] = "在下方插入空行",
  ["Flash"] = "快速跳转（Flash）",
  ["Flash Treesitter"] = "按语法结构选择（Flash）",
  ["Remote Flash"] = "远程操作（Flash）",
  ["Toggle Flash Search"] = "开关搜索时的 Flash 标签",
  ["Treesitter Incremental Selection"] = "逐级扩大选区",
  ["Select next node"] = "扩大选区到上一级语法节点",
  ["Select previous node"] = "缩小选区",
  ["MiniPairs <BS>"] = "删除成对括号",
  ["MiniPairs "] = "括号内回车换行", -- 原文 "MiniPairs <CR>"，<CR> 已被默认规则去掉

  -- ── 光标移动（Neovim 内置按键）─────────────────────────────────────────
  ["Up"] = "上",
  ["Down"] = "下",
  ["Left"] = "左",
  ["Right"] = "右",
  ["Start of line"] = "行首",
  ["Start of line (non ws)"] = "行首（第一个非空字符）",
  ["End of line"] = "行尾",
  ["First line"] = "文件第一行",
  ["Last line"] = "文件最后一行",
  ["Home line of window (top)"] = "窗口顶部行",
  ["Middle line of window"] = "窗口中间行",
  ["Last line of window"] = "窗口底部行",
  ["Next word"] = "下一个单词开头",
  ["Prev word"] = "上一个单词开头",
  ["Next end of word"] = "下一个单词结尾",
  ["Prev end of word"] = "上一个单词结尾",
  ["Next WORD"] = "下一个词（以空格分隔）",
  ["Prev WORD"] = "上一个词（以空格分隔）",
  ["Next end of WORD"] = "下一个词结尾（以空格分隔）",
  ["Next empty line"] = "下一个空行",
  ["Prev empty line"] = "上一个空行",
  ["Move to next char"] = "跳到本行下一个指定字符",
  ["Move to prev char"] = "跳到本行上一个指定字符",
  ["Move before next char"] = "跳到本行下一个指定字符之前",
  ["Move before prev char"] = "跳到本行上一个指定字符之后",
  ["Next ftFT"] = "重复上次字符跳转",
  ["Prev ftFT"] = "反向重复字符跳转",
  ["Matching (){}[]"] = "跳到配对的括号",
  ["Next unmatched group"] = "下一个未配对括号",
  ["Previous unmatched group"] = "上一个未配对括号",
  ["Next ("] = "下一个未配对的 (",
  ["Previous ("] = "上一个未配对的 (",
  ["Next {"] = "下一个未配对的 {",
  ["Previous {"] = "上一个未配对的 {",
  ["Next <"] = "下一个未配对的 <",
  ["Previous <"] = "上一个未配对的 <",
  ["Next Function Start"] = "下一个函数开头",
  ["Next Function End"] = "下一个函数结尾",
  ["Prev Function Start"] = "上一个函数开头",
  ["Prev Function End"] = "上一个函数结尾",
  ["Next Class Start"] = "下一个类开头",
  ["Next Class End"] = "下一个类结尾",
  ["Prev Class Start"] = "上一个类开头",
  ["Prev Class End"] = "上一个类结尾",
  ["Next Parameter Start"] = "下一个参数开头",
  ["Next Parameter End"] = "下一个参数结尾",
  ["Prev Parameter Start"] = "上一个参数开头",
  ["Prev Parameter End"] = "上一个参数结尾",
  ["Next method start"] = "下一个方法开头",
  ["Next method end"] = "下一个方法结尾",
  ["Previous method start"] = "上一个方法开头",
  ["Previous method end"] = "上一个方法结尾",
  ["Next misspelled word"] = "下一个拼写错误",
  ["Previous misspelled word"] = "上一个拼写错误",
  ["Go to last insert"] = "回到上次插入的位置",
  ["Go to [count] older position in change list"] = "回到更早的修改位置",
  ["Go to [count] newer position in change list"] = "前往更新的修改位置",
  ["Last visual selection"] = "重新选中上次的选区",
  ["Half screen to the left"] = "向左滚动半屏",
  ["Half screen to the right"] = "向右滚动半屏",
  ["Top this line"] = "当前行滚到顶部",
  ["Center this line"] = "当前行滚到中间",
  ["Bottom this line"] = "当前行滚到底部",
  ["Left this line"] = "当前列滚到最左",
  ["Right this line"] = "当前列滚到最右",
  ["Show cursor line"] = "显示光标所在行",

  -- ── 操作符（按下后再接一个移动或文本对象）─────────────────────────────
  ["Change"] = "修改",
  ["Delete"] = "删除",
  ["Yank"] = "复制",
  ["Replace"] = "替换字符",
  ["Visual"] = "可视模式（按字符选择）",
  ["Visual Line"] = "可视模式（按行选择）",
  ["Indent left"] = "向左缩进",
  ["Indent right"] = "向右缩进",
  ["Uppercase"] = "转为大写",
  ["Lowercase"] = "转为小写",
  ["Toggle case"] = "切换大小写",
  ["Run program"] = "通过外部程序过滤",

  -- ── 折叠 ─────────────────────────────────────────────────────────────
  ["Create fold"] = "创建折叠",
  ["Open fold under cursor"] = "展开光标处折叠",
  ["Close fold under cursor"] = "收起光标处折叠",
  ["Toggle fold under cursor"] = "展开 / 收起光标处折叠",
  ["Open all folds under cursor"] = "展开光标处所有折叠",
  ["Close all folds under cursor"] = "收起光标处所有折叠",
  ["Toggle all folds under cursor"] = "展开 / 收起光标处所有折叠",
  ["Open all folds"] = "展开全部折叠",
  ["Close all folds"] = "收起全部折叠",
  ["Fold more"] = "多收起一级",
  ["Fold less"] = "多展开一级",
  ["Delete fold under cursor"] = "删除光标处折叠",
  ["Delete all folds under cursor"] = "删除光标处所有折叠",
  ["Delete all folds in file"] = "删除文件中所有折叠",
  ["Toggle folding"] = "开关折叠功能",
  ["Update folds"] = "刷新折叠",

  -- ── 拼写 ─────────────────────────────────────────────────────────────
  ["Spelling Suggestions"] = "拼写建议",
  ["Spelling suggestions"] = "拼写建议",
  ["Add word to spell list"] = "把单词加入词典",
  ["Mark word as bad/misspelling"] = "把单词标记为拼写错误",

  -- ── 文本对象（在 d/c/y/v 之后按 i 或 a 再接以下按键）─────────────────
  ["argument"] = "函数参数",
  ["block, conditional, loop"] = "代码块 / 条件 / 循环",
  ["class"] = "类",
  ["function"] = "函数",
  ["tag"] = "HTML 标签",
  ["tag block"] = "HTML 标签块",
  ["inner tag block"] = "HTML 标签块内部",
  ["digit(s)"] = "数字",
  ["entire file"] = "整个文件",
  ["indent"] = "同级缩进块",
  ["use/call"] = "函数调用",
  ["use/call without dot"] = "函数调用（不含 . 前缀）",
  ["CamelCase / snake_case"] = "驼峰 / 下划线命名的一段",
  ["underscore"] = "下划线之间",
  ["user prompt"] = "自定义边界（按提示输入）",
  ["quote `\"'"] = "任意引号",
  ["whitespace"] = "空白",
  ["word with ws"] = "单词（含空白）",
  ["inner word"] = "单词",
  ["WORD with ws"] = "词（以空格分隔，含空白）",
  ["inner WORD"] = "词（以空格分隔）",
  ["sentence"] = "句子",
  ["inner sentence"] = "句子（不含空白）",
  ["paragraph"] = "段落",
  ["inner paragraph"] = "段落（不含空行）",
  ["\" string"] = "\" 字符串",
  ["' string"] = "' 字符串",
  ["` string"] = "` 字符串",
  ["inner \" string"] = "\" 字符串内部",
  ["inner ' string"] = "' 字符串内部",
  ["inner ` string"] = "` 字符串内部",
  ["() block"] = "() 括号块",
  ["() block with ws"] = "() 括号块（含空白）",
  ["[(]) block"] = "() 括号块",
  ["inner [(])"] = "() 括号内部",
  ["{} block"] = "{} 花括号块",
  ["{} with ws"] = "{} 花括号块（含空白）",
  ["[{]} block"] = "{} 花括号块",
  ["inner [{]}"] = "{} 花括号内部",
  ["[] block"] = "[] 方括号块",
  ["[] block with ws"] = "[] 方括号块（含空白）",
  ["inner []"] = "[] 方括号内部",
  ["<> block"] = "<> 尖括号块",
  ["<> block with ws"] = "<> 尖括号块（含空白）",
  ["inner <>"] = "<> 尖括号内部",
  [")]} block"] = "任意括号块",
  ["Move to left \"around\""] = "移到文本对象左边界",
  ["Move to right \"around\""] = "移到文本对象右边界",

  -- ── 寄存器面板（按 " 时显示）─────────────────────────────────────────
  ["last deleted, changed, or yanked content"] = "最近删除、修改或复制的内容",
  ["last yank"] = "最近复制的内容",
  ["deleted or changed content smaller than one line"] = "不足一行的删除或修改内容",
  ["last inserted text"] = "最近输入的文字",
  ["name of the current file"] = "当前文件名",
  ["most recent executed command"] = "最近执行的命令",
  ["alternate buffer"] = "上一个文件",
  ["result of an expression"] = "表达式结果",
  ["synchronized with the system clipboard"] = "系统剪贴板",
  ["synchronized with the selection clipboard"] = "选择剪贴板",
  ["black hole"] = "黑洞（丢弃内容）",
  ["last search pattern"] = "最近的搜索词",

  -- ── 标记面板（按 ' 或 ` 时显示）──────────────────────────────────────
  ["Last position of cursor in insert mode"] = "上次插入模式的光标位置",
  ["Last change in current buffer"] = "本文件最近修改的位置",
  ["Last exited current buffer"] = "上次离开本文件时的位置",
  ["In last file edited"] = "上次编辑的文件",
  ["Back to line in current buffer where jumped from"] = "跳转前所在行",
  ["Back to position in current buffer where jumped from"] = "跳转前所在位置",
  ["To beginning of previously changed or yanked text"] = "上次修改 / 复制内容的开头",
  ["To end of previously changed or yanked text"] = "上次修改 / 复制内容的结尾",
  ["To beginning of last visual selection"] = "上次选区的开头",
  ["To end of last visual selection"] = "上次选区的结尾",

  -- ── mini.pairs 自动括号（插入模式）────────────────────────────────────
  ["Open action for \"()\" pair"] = "自动补全 ()",
  ["Open action for \"[]\" pair"] = "自动补全 []",
  ["Open action for \"{}\" pair"] = "自动补全 {}",
  ["Close action for \"()\" pair"] = "跳过右括号 )",
  ["Close action for \"[]\" pair"] = "跳过右括号 ]",
  ["Close action for \"{}\" pair"] = "跳过右括号 }",
  ["Closeopen action for '\"\"' pair"] = "自动补全双引号",
  ["Closeopen action for \"''\" pair"] = "自动补全单引号",
  ["Closeopen action for \"``\" pair"] = "自动补全反引号",

  -- ── 快速修复列表（Neovim 内置 [q ]q 等，原文为命令名）─────────────────
  ["crewind"] = "快速修复：第一项",
  ["clast"] = "快速修复：最后一项",
  ["cpfile"] = "快速修复：上一个文件",
  ["cnfile"] = "快速修复：下一个文件",
  ["lrewind"] = "位置列表：第一项",
  ["llast"] = "位置列表：最后一项",
  ["lprevious"] = "位置列表：上一项",
  ["lnext"] = "位置列表：下一项",
  ["lpfile"] = "位置列表：上一个文件",
  ["lnfile"] = "位置列表：下一个文件",
  ["trewind"] = "标签栈：第一个",
  ["tlast"] = "标签栈：最后一个",
  ["ptprevious"] = "预览标签：上一个",
  ["ptnext"] = "预览标签：下一个",

  -- ── 搜索窗口 / 文件树（snacks picker、explorer）里的按键，原文为动作名 ──────
  ["cancel"] = "取消",
  ["close"] = "关闭",
  ["Close"] = "关闭",
  ["confirm"] = "打开 / 确认",
  ["cycle_win"] = "切换到下一个窗格",
  ["delete word"] = "删除前一个单词",
  ["edit_split"] = "在下方分屏打开",
  ["edit_vsplit"] = "在右侧分屏打开",
  ["tab"] = "在新标签页打开",
  ["pick_win, jump"] = "选择窗口后打开",
  ["flash"] = "快速跳转到列表项（Flash）",
  ["focus_input"] = "聚焦到输入框",
  ["history_back"] = "上一条搜索历史",
  ["history_forward"] = "下一条搜索历史",
  ["insert_alt"] = "插入上一个文件的文件名",
  ["insert_cword"] = "插入光标处的单词",
  ["insert_cWORD"] = "插入光标处的词（以空格分隔）",
  ["insert_file"] = "插入光标处的文件路径",
  ["insert_file_full"] = "插入光标处文件的完整路径",
  ["insert_filename"] = "插入当前文件名",
  ["insert_line"] = "插入当前行",
  ["inspect"] = "查看条目详情（调试用）",
  ["layout_top"] = "布局：放到顶部",
  ["layout_bottom"] = "布局：放到底部",
  ["layout_left"] = "布局：放到左侧",
  ["layout_right"] = "布局：放到右侧",
  ["list_up"] = "上一项",
  ["list_down"] = "下一项",
  ["list_top"] = "跳到列表顶部",
  ["list_bottom"] = "跳到列表底部",
  ["list_scroll_up"] = "列表向上滚动",
  ["list_scroll_down"] = "列表向下滚动",
  ["list_scroll_top"] = "当前项滚到顶部",
  ["list_scroll_center"] = "当前项滚到中间",
  ["list_scroll_bottom"] = "当前项滚到底部",
  ["preview_scroll_up"] = "预览向上滚动",
  ["preview_scroll_down"] = "预览向下滚动",
  ["picker_grep"] = "在此目录中全文搜索",
  ["print_path"] = "显示文件路径",
  ["qflist"] = "发送到快速修复列表",
  ["select_all"] = "全选",
  ["select_and_next"] = "选中并移到下一项",
  ["select_and_prev"] = "选中并移到上一项",
  ["tcd"] = "把当前标签页的工作目录切换到此处",
  ["terminal"] = "在此目录打开终端",
  ["toggle_cwd"] = "切换搜索范围（项目根目录 / 当前目录）",
  ["toggle_focus"] = "在输入框和列表之间切换",
  ["toggle_follow"] = "开关：跟随符号链接",
  ["toggle_help_input"] = "显示 / 隐藏帮助",
  ["toggle_help_list"] = "显示 / 隐藏帮助",
  ["toggle_hidden"] = "开关：显示隐藏文件",
  ["toggle_ignored"] = "开关：显示被 Git 忽略的文件",
  ["toggle_live"] = "开关：实时搜索",
  ["toggle_maximize"] = "最大化 / 还原",
  ["toggle_preview"] = "开关：预览窗口",
  ["toggle_regex"] = "开关：正则表达式",
  ["trouble_open"] = "在 Trouble 面板中打开",
  ["explorer_add"] = "新建文件（以 / 结尾则新建目录）",
  ["explorer_del"] = "删除（不进回收站，无法恢复）",
  ["explorer_rename"] = "重命名",
  ["explorer_yank"] = "复制所选文件（之后用“粘贴”放到别处）",
  ["explorer_paste"] = "粘贴已复制的文件",
  ["explorer_copy"] = "复制所选文件到此处",
  ["explorer_move"] = "移动所选文件到此处",
  ["explorer_open"] = "用系统程序打开",
  ["explorer_up"] = "上一级目录",
  ["explorer_focus"] = "以此目录为根",
  ["explorer_close"] = "收起目录",
  ["explorer_close_all"] = "收起全部目录",
  ["explorer_update"] = "刷新",
  ["explorer_git_next"] = "下一个有 Git 改动的文件",
  ["explorer_git_prev"] = "上一个有 Git 改动的文件",
  ["explorer_diagnostic_next"] = "下一个有诊断的文件",
  ["explorer_diagnostic_prev"] = "上一个有诊断的文件",
  ["explorer_error_next"] = "下一个有错误的文件",
  ["explorer_error_prev"] = "上一个有错误的文件",
  ["explorer_warn_next"] = "下一个有警告的文件",
  ["explorer_warn_prev"] = "上一个有警告的文件",

  -- ── Lazy 插件管理界面（:Lazy）────────────────────────────────────────
  ["Install missing plugins"] = "安装缺失的插件",
  ["Install a plugin"] = "安装此插件",
  ["Update plugins. This will also update the lockfile"] = "更新全部插件（会改写锁文件 lazy-lock.json）",
  ["Update a plugin. This will also update the lockfile"] = "更新此插件（会改写锁文件 lazy-lock.json）",
  ["Run install, clean and update"] = "同步：安装、清理并更新（会改写锁文件）",
  ["Clean plugins that are no longer needed"] = "清理不再需要的插件",
  ["Check for updates and show the log (git fetch)"] = "检查更新并显示日志（git fetch）",
  ["Updates all plugins to the state in the lockfile. For a single plugin: restore it to the state in the lockfile or to a given commit under the cursor"] = "恢复到锁文件记录的版本（光标在某插件上时只恢复该插件）",
  ["Restore"] = "恢复到锁文件记录的版本",
  ["Delete a plugin. WARNING: this will delete the plugin even if it should be installed!"] = "删除此插件（即使配置中仍需要它！）",
  ["Abort"] = "中止当前操作",
  ["Details"] = "插件详情",
  ["Diff"] = "查看改动",
  ["Inspect Plugin"] = "查看插件内部信息",
  ["Next Plugin"] = "下一个插件",
  ["Prev Plugin"] = "上一个插件",
  ["Go back to plugin list"] = "返回插件列表",
  ["Open lazygit log"] = "在 lazygit 中查看提交记录",
  ["Open terminal in plugin dir"] = "在插件目录打开终端",
  ["Show recent updates"] = "显示最近的更新",
  ["Show debug information"] = "显示调试信息",
  ["Show detailed profiling"] = "显示详细的启动性能分析",
  ["Filter Profile"] = "过滤性能分析结果",
  ["Sort Profile"] = "排序性能分析结果",
  ["Toggle this help page"] = "显示 / 隐藏帮助",
}

-- 开关类按键：原文为 "Enable xxx" / "Disable xxx"
M.toggles = {
  ["Animations"] = "动画",
  ["Auto Format (Buffer)"] = "保存时自动格式化（当前文件）",
  ["Auto Format (Global)"] = "保存时自动格式化（全局）",
  ["Conceal Level"] = "隐藏标记符号",
  ["Dark Background"] = "深色背景",
  ["Diagnostics"] = "诊断提示",
  ["Dimming"] = "淡化非当前代码",
  ["Git Signs"] = "Git 改动标记",
  ["Indent Guides"] = "缩进参考线",
  ["Inlay Hints"] = "内联类型提示",
  ["Line Numbers"] = "行号",
  ["Mini Pairs"] = "自动补全括号",
  ["Profiler"] = "性能分析",
  ["Profiler Highlights"] = "性能分析高亮",
  ["Relative Number"] = "相对行号",
  ["Smooth Scroll"] = "平滑滚动",
  ["Spelling"] = "拼写检查",
  ["Tabline"] = "顶部标签栏",
  ["Treesitter Highlight"] = "语法高亮（Treesitter）",
  ["Wrap"] = "自动换行显示",
  ["Zen Mode"] = "专注模式",
  ["Zoom Mode"] = "窗口最大化",
}

-- 规律性文字（Lua 模式 → 替换结果）
M.patterns = {
  -- 分组下没有说明时显示的数量，如 "3 keymaps"
  { "^(%d+) keymaps?$", "%1 个快捷键" },
  -- Neovim 内置默认映射，原文形如 "help Y-default"
  { "^help (.+)%-default$", "Neovim 内置（:help %1）" },
}

-- which-key 底部帮助栏
M.help = {
  close = "关闭",
  back = "返回上级",
  scroll = "滚动",
}

---@param desc string
---@return string
function M.translate(desc)
  local zh = M.exact[desc]
  if zh then
    return zh
  end
  local verb, name = desc:match("^(%a+) (.+)$")
  if (verb == "Enable" or verb == "Disable") and M.toggles[name] then
    return (verb == "Enable" and "启用" or "禁用") .. M.toggles[name]
  end
  for _, p in ipairs(M.patterns) do
    local out, n = desc:gsub(p[1], p[2])
    if n > 0 then
      return out
    end
  end
  return desc
end

return M
