set -g mouse on
set -g default-terminal "tmux-256color"

set -s set-clipboard on
set -ga terminal-features ',*:clipboard'
set -g allow-passthrough on
# # Options to make tmux more pleasant
# # Load catppuccin
run ~/.local/share/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_status_background "none"
# set -g @catppuccin_window_status_style "none"
# set -g @catppuccin_pane_status_enabled "off"
# set -g @catppuccin_pane_border_status "off"

# status left look and feel
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_green},fg=#{@thm_crust}] 󰿨 #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}] 󰿨 #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_surface_1},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_teal}]  #{pane_current_command} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_surface_1},none]│"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_blue}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_surface_1},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag,  zoom ,}"

# status right look and feel
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_peach}]    #{host_short} "
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_surface_1},none]│"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_lavender}] 󰭦 %Y-%m-%d 󰅐 %H:%M "

# Configure Tmux
set -g status-position top
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

# pane border look and feel
setw -g pane-border-status top
setw -g pane-border-format "#{?pane_active,#{?#{!=:#{pane_title},#{host_short}},   #{pane_index} #{pane_title} ,   #{pane_index} },#{?#{!=:#{pane_title},#{host_short}}, #{pane_index} #{pane_title} , #{pane_index} }}"
setw -g pane-active-border-style "fg=#{@thm_mauve},dim"
setw -g pane-border-style "fg=#{@thm_overlay_0}"
setw -g pane-border-lines single

# window look and feel
set -wg automatic-rename on
set -g automatic-rename-format "Window"

set -g window-status-format "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]#[bg=#{@thm_overlay_0},fg=#{@thm_subtext_1}]#{?#{!=:#{window_name},Window}, #W , #I }#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]"

set -gF window-status-separator "#[bg=#{@thm_bg}] "

set -g window-status-current-format "#[bg=#{@thm_bg},fg=#{@thm_mauve}]#[bg=#{@thm_mauve},fg=#{@thm_bg}]#{?#{!=:#{window_name},Window}, #W , #I }#[bg=#{@thm_bg},fg=#{@thm_mauve}]"

bind R source-file ~/.config/tmux/tmux.conf \; display "config reloaded"
